apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    safe.k8s.fmeflow.component: data
    {{- include "fmeflow.common.labels" . | indent 4 }}
  name: fmeflow-data
spec:
  {{- with .Values.storage }}
  accessModes:
  - {{ .fmeflow.accessMode }}
  {{- if and (not .useHostDir) .fmeflow.class }}
  storageClassName: {{ .fmeflow.class }}
  {{- end }}
  resources:
    requests:
      storage: {{ .fmeflow.size }}
  {{- if .fmeflow.existingPersistentVolume }}
  volumeName: {{ .fmeflow.existingPersistentVolume }}
  {{- end }}
  {{- end }}
